
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RobotAPIImplService", targetNamespace = "http://webservice/", wsdlLocation = "http://192.168.200.172:8080/WS/RobotAPI?wsdl")
public class RobotAPIImplService
    extends Service
{

    private final static URL ROBOTAPIIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROBOTAPIIMPLSERVICE_EXCEPTION;
    private final static QName ROBOTAPIIMPLSERVICE_QNAME = new QName("http://webservice/", "RobotAPIImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.200.172:8080/WS/RobotAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROBOTAPIIMPLSERVICE_WSDL_LOCATION = url;
        ROBOTAPIIMPLSERVICE_EXCEPTION = e;
    }

    public RobotAPIImplService() {
        super(__getWsdlLocation(), ROBOTAPIIMPLSERVICE_QNAME);
    }

    public RobotAPIImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROBOTAPIIMPLSERVICE_QNAME, features);
    }

    public RobotAPIImplService(URL wsdlLocation) {
        super(wsdlLocation, ROBOTAPIIMPLSERVICE_QNAME);
    }

    public RobotAPIImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROBOTAPIIMPLSERVICE_QNAME, features);
    }

    public RobotAPIImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RobotAPIImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RobotAPI
     */
    @WebEndpoint(name = "RobotAPIImplPort")
    public RobotAPI getRobotAPIImplPort() {
        return super.getPort(new QName("http://webservice/", "RobotAPIImplPort"), RobotAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RobotAPI
     */
    @WebEndpoint(name = "RobotAPIImplPort")
    public RobotAPI getRobotAPIImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "RobotAPIImplPort"), RobotAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROBOTAPIIMPLSERVICE_EXCEPTION!= null) {
            throw ROBOTAPIIMPLSERVICE_EXCEPTION;
        }
        return ROBOTAPIIMPLSERVICE_WSDL_LOCATION;
    }

}
